name: dart_amqp
description: >
  Dart AMQP client implementing protocol version 0.9.1
version: 0.1.3
author: Achilleas Anagnostopoulos
homepage: https://github.com/achilleasa/dart_amqp
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  logging: ^0.11.3+2
dev_dependencies:
  test: ^1.9.3
  mockito: ^3.0.0
  http: ^0.11.1+1
  xml: ^3.2.0
  coverage: ^0.13.3
  coveralls: ^3.2.0
  pedantic: 1.5.0
